version: "3.8"

services:
    java:
      build:
        context: .
      ports:
        - "8080:8080"
      environment:
        - POSTGRES_DB=sc-api-springboot
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=docker
    postgres:
      container_name: sc-api-springboot
      image: postgres
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: docker
        POSTGRES_DB: sc-api-springboot